# specify a directory to install
cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'crisidev/homebrew-chunkwm'
tap 'koekeishiya/formulae'
tap 'bazelbuild/tap'

brew 'awscli'
brew 'chunkwm'
brew 'coreutils'
brew 'erlang'
brew 'exercism'
brew 'fzf'
brew 'gdb'
brew 'gdbm'
brew 'git'
brew 'gpg'
brew 'graphviz'
brew 'heroku'
brew 'jq'
brew 'koekeishiya/formulae/skhd'
brew 'neovim'
brew 'nomad'
brew 'packer'
brew 'postgresql'
brew 'ripgrep'
brew 'ruby'
brew 'sbt'
brew 'scala'
brew 'terraform'
brew 'terraform_landscape'
brew 'tree'
brew 'vim'
brew 'zsh'
brew 'bazelbuild/tap/bazel'

# Casks
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'kindle'
cask 'postman'
cask 'slack'
cask 'spotify'
cask 'atom'
